tap "homebrew/cask-fonts"

brew "bat"
brew "curl"
brew "diff-so-fancy"
brew "fzf"
brew "git"
brew "gh"
brew "gnugp"
brew "imagemagick", args: ["with-libheif", "with-webp"]
brew "ffmpeg", args: ["with-libvpx"]
brew "ncdu"
brew "nvm"
brew "pgcli"
brew "python"
brew "the_silver_searcher"
brew "thefuck"
brew "trash"
brew "tree"
brew "youtube-dl"
brew "wget"
brew "z"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "zsh"

cask "alfred3"
cask "docker"
cask "font-fira-code"
cask "google-chrome"
cask "imageoptim"
cask "iterm2"
cask "postman"
cask "spectacle"
cask "spotify"
cask "visual-studio-code"
cask "vlc"
